// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHdPn4eTLfAOKOF-olpDgjHHc4O-sWyg4',
    appId: '1:262987420661:web:889bd8e080aef7cd8ac6bc',
    messagingSenderId: '262987420661',
    projectId: 'register-form-3d855',
    authDomain: 'register-form-3d855.firebaseapp.com',
    storageBucket: 'register-form-3d855.firebasestorage.app',
    measurementId: 'G-WJ91YD7ZX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS--QSOEmzb8BiJl8V0cdZ4YQ5ObyVsOM',
    appId: '1:262987420661:android:7a7033052e7b9a9a8ac6bc',
    messagingSenderId: '262987420661',
    projectId: 'register-form-3d855',
    storageBucket: 'register-form-3d855.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9iyDm535InRT4-73cVmIUeVi3OqGwbE',
    appId: '1:262987420661:ios:b391ca6d7d765c238ac6bc',
    messagingSenderId: '262987420661',
    projectId: 'register-form-3d855',
    storageBucket: 'register-form-3d855.firebasestorage.app',
    iosBundleId: 'com.example.registerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ9iyDm535InRT4-73cVmIUeVi3OqGwbE',
    appId: '1:262987420661:ios:b391ca6d7d765c238ac6bc',
    messagingSenderId: '262987420661',
    projectId: 'register-form-3d855',
    storageBucket: 'register-form-3d855.firebasestorage.app',
    iosBundleId: 'com.example.registerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHdPn4eTLfAOKOF-olpDgjHHc4O-sWyg4',
    appId: '1:262987420661:web:14648b17c95d8c148ac6bc',
    messagingSenderId: '262987420661',
    projectId: 'register-form-3d855',
    authDomain: 'register-form-3d855.firebaseapp.com',
    storageBucket: 'register-form-3d855.firebasestorage.app',
    measurementId: 'G-MC7PZT51FK',
  );
}
